[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easybench = "1.1.0"
mpi = { version = "0.6", features = ["user-operations", "derive"] }